// This file has been generated by Tauri Specta. Do not edit this file manually.


/* Types */
export type AppSettings = {
	llm_provider: string,
	llm_model: string,
	llm_api_key: string,
	llm_base_url: string,
	embed_provider: string,
	embed_model: string,
	embed_api_key: string,
	embed_base_url: string,
	image_provider: string,
	image_model: string,
	image_api_key: string,
	image_base_url: string,
	tts_provider: string,
	tts_api_key: string,
	tts_voice: string,
	stt_provider: string,
	stt_api_key: string,
};

export type CampaignNote = {
	id: string,
	title: string,
	path: string,
	frontmatter: { [key in string]: unknown },
	content: string,
};

/**  Represents metadata and script content for a loaded plugin. */
export type PluginInfo = {
	/**  Unique identifier for the plugin (e.g. `"dice-roller"`). */
	id: string,
	/**  Human-readable display name. */
	name: string,
	/**  Semantic version string. */
	version: string,
	/**  Short description of plugin features. */
	description: string,
	/**  Explicit permission requests declared in `manifest.json`. */
	permissions: string[],
	/**  Raw JavaScript code loaded from the entry file (e.g. `index.js`). */
	script_content: string,
	/**  Flag indicating whether the plugin is enabled for execution. */
	active: boolean,
};

export type RuleEntry = {
	id: string,
	path: string,
	title: string,
	category: string,
	source: string,
	content: string,
};

export type SearchResult = {
	type: string,
	title: string,
	snippet: string,
	score: number | null,
	path: string,
};

export type TemplateAction = {
	label: string,
	hook: string,
	plugin: string,
};

export type TemplateEntry = {
	name: string,
	properties: { [key in string]: TemplateProperty },
	actions: TemplateAction[],
};

export type TemplateProperty = {
	type: string,
	default: unknown,
};

export type VaultSettings = {
	name: string | null,
	campaign_system: string | null,
	description: string | null,
	tag_colors: { [key in string]: string } | null,
};

