// This file has been generated by Tauri Specta. Do not edit this file manually.


/* Types */
export type AppSettings = {
	llm_provider: string,
	llm_model: string,
	llm_api_key: string,
	llm_base_url: string,
	embed_provider: string,
	embed_model: string,
	embed_api_key: string,
	embed_base_url: string,
	image_provider: string,
	image_model: string,
	image_api_key: string,
	image_base_url: string,
	tts_provider: string,
	tts_api_key: string,
	tts_voice: string,
	stt_provider: string,
	stt_api_key: string,
	stt_base_url: string,
	allow_local_providers: boolean,
};

export type CampaignNote = {
	id: string,
	title: string,
	path: string,
	frontmatter: { [key in string]: unknown },
	content: string,
};

/**  A single note-type registry entry declared by a world's manifest. */
export type NoteType = {
	id: string,
	label: string,
	color: string,
};

/**
 *  PluginInfo mirrors the runtime type in `plugins.rs` so it can be exported to TypeScript.
 *  It is kept minimal because Specta only needs the public shape.
 */
export type PluginInfo = {
	id: string,
	name: string,
	version: string,
	description: string,
	permissions: string[],
	script_content: string,
	active: boolean,
};

/**  A single provenance-taxonomy entry declared by a world's manifest. */
export type ProvenanceType = {
	id: string,
	label: string,
};

export type RuleEntry = {
	id: string,
	path: string,
	title: string,
	category: string,
	source: string,
	content: string,
};

export type SearchResult = {
	type: string,
	title: string,
	snippet: string,
	score: number | null,
	path: string,
};

export type SourceEntry = {
	id: string,
	title: string,
	author: string,
	source_type: string,
	url: string,
	date: string,
};

export type TemplateAction = {
	label: string,
	hook: string,
	plugin: string,
};

export type TemplateEntry = {
	name: string,
	properties: { [key in string]: TemplateProperty },
	actions: TemplateAction[],
};

export type TemplateProperty = {
	type: string,
	default: unknown,
};

export type VaultSettings = {
	name: string | null,
	campaign_system: string | null,
	description: string | null,
	tag_colors: { [key in string]: string } | null,
};

/**
 *  Result of a web clipping operation: the fetched page's readable content
 *  converted to clean Markdown, plus provenance metadata.
 */
export type WebClip = {
	title: string,
	site: string,
	url: string,
	markdown: string,
	fetched_at: string,
};

/**  Lightweight identity for the World Shelf (switcher) UI. */
export type WorldInfo = {
	id: string,
	name: string,
	description: string,
	icon: string,
	path: string,
	last_opened: string | null,
};

/**
 *  The world object's manifest (`world.json`). Declares a world's identity,
 *  theme, note-type registry, provenance taxonomy, and bible conditioning flag.
 */
export type WorldManifest = {
	id: string,
	name: string,
	description: string,
	icon: string,
	theme: WorldTheme,
	note_types: NoteType[],
	provenance_taxonomy: ProvenanceType[],
	bible: boolean,
	created: string,
};

/**  Per-world theme overrides layered on top of the global Ledger tokens. */
export type WorldTheme = {
	palette: string | null,
	accent: string | null,
	serif: boolean | null,
};

