import type { CampaignNote as GeneratedCampaignNote, RuleEntry as GeneratedRuleEntry, SearchResult as GeneratedSearchResult } from './bindings';

/**
 * Strongly-typed wrapper around the Specta-generated CampaignNote.
 *
 * `frontmatter` is intentionally `Record<string, unknown>` because note metadata keys are
 * user-defined and may hold strings, numbers, booleans, arrays, or nested JSON values.
 * Callers should narrow values with `String(...)`, `Array.isArray(...)`, or `typeof` checks.
 */
export type CampaignNote = Omit<GeneratedCampaignNote, 'frontmatter'> & {
  frontmatter: Record<string, unknown>;
};

export type RuleEntry = GeneratedRuleEntry;

/**
 * Discriminated union narrowing the generated `SearchResult.type` to the only two runtime
 * values ever emitted by the backend ("note" and "rule").
 */
export type SearchResult = Omit<GeneratedSearchResult, 'type' | 'score'> & {
  type: 'note' | 'rule';
  score: number;
};

/**
 * A captured source (web page, book, article) that notes can be attributed to.
 * Defined locally until the Specta-generated bindings are regenerated by the
 * backend build. Provenance is stored in note frontmatter under the
 * `source_*` keys.
 */
export interface SourceEntry {
  id: string;
  title: string;
  author: string;
  source_type: string; // canon | history | invention | custom
  url: string;
  date: string;
}

/**
 * Result of clipping a web page via the backend `clip_webpage` command.
 */
export interface WebClip {
  title: string;
  site: string;
  url: string;
  markdown: string;
  fetched_at: string;
}

/** The canonical provenance source types offered in the UI. */
export const SOURCE_TYPES = ["canon", "history", "invention"] as const;

/** Frontmatter keys that carry provenance metadata on a note. */
export const PROVENANCE_KEYS = [
  "source_type",
  "source_title",
  "source_author",
  "source_url",
  "source_date",
  "source_id",
] as const;
