import type { CampaignNote as GeneratedCampaignNote, RuleEntry as GeneratedRuleEntry, SearchResult as GeneratedSearchResult } from './bindings';

/**
 * Strongly-typed wrapper around the Specta-generated CampaignNote.
 *
 * `frontmatter` is intentionally `Record<string, unknown>` because note metadata keys are
 * user-defined and may hold strings, numbers, booleans, arrays, or nested JSON values.
 * Callers should narrow values with `String(...)`, `Array.isArray(...)`, or `typeof` checks.
 */
export type CampaignNote = Omit<GeneratedCampaignNote, 'frontmatter'> & {
  frontmatter: Record<string, unknown>;
};

export type RuleEntry = GeneratedRuleEntry;

/**
 * Discriminated union narrowing the generated `SearchResult.type` to the only two runtime
 * values ever emitted by the backend ("note" and "rule").
 */
export type SearchResult = Omit<GeneratedSearchResult, 'type' | 'score'> & {
  type: 'note' | 'rule';
  score: number;
};

/**
 * A captured source (web page, book, article) that notes can be attributed to.
 * Defined locally until the Specta-generated bindings are regenerated by the
 * backend build. Provenance is stored in note frontmatter under the
 * `source_*` keys.
 */
export interface SourceEntry {
  id: string;
  title: string;
  author: string;
  source_type: string; // canon | history | invention | custom
  url: string;
  date: string;
}

/**
 * Result of clipping a web page via the backend `clip_webpage` command.
 */
export interface WebClip {
  title: string;
  site: string;
  url: string;
  markdown: string;
  fetched_at: string;
}

/** The canonical provenance source types offered in the UI. */
export const SOURCE_TYPES = [
  "canon",
  "history",
  "invention",
  "speculation",
] as const;

/**
 * A note type declared by a world's manifest. Replaces the hardcoded five
 * legacy types in the graph/canvas/metadata UI. Falls back to
 * DEFAULT_NOTE_TYPES for legacy vaults.
 */
export interface NoteType {
  id: string;
  label: string;
  color: string;
}

/** A provenance state declared by a world's manifest. */
export interface ProvenanceType {
  id: string;
  label: string;
}

/** Per-world theme overrides resolved on top of the global Ledger tokens. */
export interface WorldTheme {
  palette?: string;
  accent?: string;
  serif?: boolean;
}

/** The world object: a folder (`campaigns/<world>/`) with a `world.json`. */
export interface WorldManifest {
  id: string;
  name: string;
  description: string;
  icon: string;
  theme: WorldTheme;
  note_types: NoteType[];
  provenance_taxonomy: ProvenanceType[];
  bible: boolean;
  created: string;
}

/** Lightweight world listing for the World Shelf (excludes `_liminal`). */
export interface WorldInfo {
  id: string;
  name: string;
  description: string;
  icon: string;
  path: string;
  last_opened: string | null;
}

/** Default note types — the legacy five, used when a world declares none. */
export const DEFAULT_NOTE_TYPES: NoteType[] = [
  { id: "npc", label: "Person", color: "oklch(60% 0.22 340)" },
  { id: "location", label: "Place", color: "oklch(65% 0.2 260)" },
  { id: "faction", label: "Org", color: "oklch(60% 0.15 80)" },
  { id: "item", label: "Object", color: "oklch(70% 0.18 140)" },
  { id: "event", label: "Beat", color: "oklch(75% 0.15 320)" },
];

/** Default provenance taxonomy — includes `speculation` (the Provisional). */
export const DEFAULT_PROVENANCE_TAXONOMY: ProvenanceType[] = [
  { id: "canon", label: "Canon" },
  { id: "history", label: "History" },
  { id: "invention", label: "Invention" },
  { id: "speculation", label: "Speculative" },
];

/** Frontmatter keys that carry provenance metadata on a note. */
export const PROVENANCE_KEYS = [
  "source_type",
  "source_title",
  "source_author",
  "source_url",
  "source_date",
  "source_id",
] as const;
